theme: jekyll-theme-cayman
gems:  jekyll-seo-tag

title: ASP.NET Connector SAML SP Single Sign-On(SSO) # PAge title
author: miniOrange # author name
email: info@miniorange.com # author email
description: "miniOrange ASP.NET Connector provides enterprise users Single Sign On (SSO) into your ASP.NET Web Application with 1 set of login credentials."
keywords: "saml,asp.net,asp dotnet,asp.net saml,asp dotnet saml,saml sp,saml sp initiated,asp dotnet,saml connector,asp.net connector,asp dotnet connector,dotnet saml connector,dotnet saml sp connector,asp.net saml sp sso connector,asp.net connector saml,asp dotnet connector saml,asp dotnet saml sp sso connector, asp dotnet connector saml sp sso,asp.net connector saml sp sso,single sign on,single sign on(sso),saml2 sp sso,saml2 sp single sign on,service provider initiated,asp.net connector saml2 sp initiated sso,asp dotnet connector saml2 sp initiated sso" # html meta keywords
